---
languageCode: "en-us"
title: "FPV Racing Resources"
baseurl: "https://andyshinn.github.io/fpv-racing-resources/"
theme: "drone"
metaDataFormat: "yaml"
publishDir: "docs"
sectionPagesMenu: "main"
disqusShortname: "fpv-racing-resources"
taxonomies:
  tag: "tags"
  category: "categories"
