version: 2
jobs:
  build:
    docker:
      - image: jojomi/hugo:0.19
    working_directory: /src
    steps:
      - run: apk add --no-cache git openssh-client
      - checkout
      - run: hugo
      - store_artifacts:
          path: /src/docs
          destination: html
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" -a -n "$(git status --porcelain -- docs)" ]; then
              git config --global user.email "circleci@circleci.com"
              git config --global user.name "CircleCI"
              git add docs
              git commit -m "[ci skip] publish from CircleCI"
              git push origin master
            fi
